include:
  - project: 'sygnum/infra/templates'
    ref: 'v0.8.2'
    file: '/gitlab/.ethereum-contracts-ci-template.yml'

stages:
  - solidity-build
  - solidity-tests
  - npm-publish
  - deploy-to-ropsten
  - deploy-to-mainnet

solidity-build:
  extends: .solidity-build
 
solidity-test:
  extends: .solidity-test

solidity-coverage:
  extends: .solidity-coverage

solidity-uml:
  extends: .solidity-uml

solidity-mythril:
  extends: .solidity-mythril

solidity-securify:
  extends: .solidity-securify

solidity-slither:
  extends: .solidity-slither

deploy-to-dev:
  extends: .deploy-to-dev

deploy-to-tst:
  extends: .deploy-to-tst

topup-ropsten:
  extends: .topup-ropsten

npm-publish:
  image: aob-sygnum-int-docker.bin.swisscom.com/alpine-node:12.16
  stage: npm-publish
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'>.npmrc
    - npm publish
  only:
    - master
    - develop
  tags:
    - aws
    - docker
    - spot
    - sygnum

deploy-to-prd:
  extends: .deploy-to-prd